[package]
name = "bio-node-cli"
version = "0.1.0"
edition = "2021"
authors = ["Bio P2P Team"]
description = "Command-line interface and daemon for Bio P2P Node"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bio-p2p/bio-p2p"
documentation = "https://docs.rs/bio-node-cli"
readme = "README.md"
keywords = ["p2p", "biological", "distributed", "networking", "cli"]
categories = ["command-line-utilities", "network-programming", "distributed-systems"]

[[bin]]
name = "bio-node"
path = "src/main.rs"

[features]
default = ["daemon", "metrics", "health-check"]

# Optional daemon background mode support (Unix only)
daemon = ["dep:daemonize"]

# Prometheus metrics support
metrics = ["dep:prometheus", "dep:warp"]

# HTTP health check endpoints
health-check = ["dep:warp", "dep:serde_json"]

# Development features
dev = ["tracing-subscriber/env-filter"]

[dependencies]
# Core Bio P2P components
bio-p2p-core = { path = "../bio-p2p-core", version = "0.1.0" }
bio-p2p-p2p = { path = "../bio-p2p-p2p", version = "0.1.0" }  
bio-p2p-security = { path = "../bio-p2p-security", version = "0.1.0" }
bio-p2p-resource = { path = "../bio-p2p-resource", version = "0.1.0" }

# CLI and configuration
clap = { version = "4.4", features = ["derive", "env", "wrap_help"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

# Async runtime and utilities
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
anyhow = "1.0"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = "0.2"

# Networking
libp2p = { version = "0.53", default-features = false, features = [
    "tcp", "noise", "yamux", "gossipsub", "mdns", "identify", "ping", "kad",
    "request-response", "floodsub", "dcutr", "upnp"
]}

# Serialization and data handling
serde_json = "1.0"
bincode = "1.3"
uuid = { version = "1.0", features = ["v4", "serde"] }

# Time and date handling
chrono = { version = "0.4", features = ["serde"] }

# Signal handling and process management
signal-hook = "0.3"
nix = { version = "0.27", features = ["signal", "unistd"] }

# HTTP server for health/metrics (optional)
warp = { version = "0.3", optional = true }
reqwest = { version = "0.11", features = ["json"] }

# Metrics collection (optional)
prometheus = { version = "0.13", optional = true }

# Daemon support (optional, Unix only)
daemonize = { version = "0.5", optional = true }

# System information
sysinfo = "0.29"

[target.'cfg(windows)'.dependencies]
# Windows-specific dependencies
winapi = { version = "0.3", features = ["winuser", "processthreadsapi"] }

[target.'cfg(unix)'.dependencies]
# Unix-specific dependencies for enhanced daemon support
libc = "0.2"

[dev-dependencies]
tempfile = "3.0"
tokio-test = "0.4"
criterion = { version = "0.5", features = ["html_reports"] }
test-log = "0.2"

[build-dependencies]
built = { version = "0.7", features = ["chrono", "git2"] }

[[bench]]
name = "node_performance"
harness = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]